export const PokemonType: Record<string,string> = {
	normal: "一般",
	fighting: "格斗",
	flying: "飞行",
	poison: "毒",
	ground: "地面",
	rock: "岩石",
	bug: "虫",
	ghost: "幽灵",
	steel: "钢",
	fire: "火",
	water: "水",
	grass: "草",
	electric: "电",
	psychic: "超能力",
	ice: "冰",
	dragon: "龙",
	dark: "恶",
	fairy: "妖精",
}

export const PokemenTypeColor: Record<string, string> = {
	"火": "#FF4422",
	"草": "#77CC55",
	"水": "#3399FF",
	"地面": "#DDBB55",
	"飞行": "#6699FF",
	"电": "#FFCC33",
	"一般": "#BBBBAA",
	"毒": "#AA5599",
	"妖精": "#FFAAFF",
	"恶": "#50413f",
	"幽灵": "#704170",
	"虫": "#91a119",
	"岩石": "#afa981",
	"钢": "#60a1b8",
	"格斗": "#ff8000",
	"冰": "#3fd8ff",
	"超能力": "#ef4179",
	"龙": "#5060e1",
}