name: Deployment

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # build
      - uses: actions/checkout@master
      - name: Use Node version 18+
        uses: actions/setup-node@master
        with:
          node-version: 18.18.2
      - name: install libs
        run: npm install
      - name: build application
        run: npm run build
      - name: delete cache
        run: |
          cd ./.next
          rm -rf cache
          cd ../
      - name: tarser
        run: tar -zcvf release.tgz .next next.config.mjs package.json public
      # create release
      - name: create release
        id: create_release
        uses: actions/create-release@master
        env:
          GITHUB_TOKEN: ${{secrets.TOKEN}}
        with:
          tag_name: ${{github.ref}}
          release_name: Release ${{github.ref}}
          draft: false
          prerelease: false

      # upload release
      - name: upload release
        id: upload_release
        uses: actions/upload-release-asset@master
        env:
          GITHUB_TOKEN: ${{secrets.TOKEN}}
        with:
          upload_url: ${{steps.create_release.outputs.upload_url}}
          asset_path: ./release.tgz
          asset_name: release.tgz
          asset_content_type: application/x-tgz

  deploy:
    needs: build
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.HOST}}
          username: ${{secrets.USERNAME}}
          password: ${{secrets.PASSWORD}}
          port: ${{secrets.PORT}}
          script: |
            cd /www/new_next_blog
            rm -rf .next
            wget https://github.com/Dr-ZHUIM/zhuim-knowledge-platform-refactor-version/releases/latest/download/release.tgz -O release.tgz
            tar zxvf release.tgz
            npm i

